/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
// Return empty map during E2E tests to prevent module loading issues
export const CalendarServiceMap = process.env.NEXT_PUBLIC_IS_E2E
  ? {}
  : {
      amie: import("./amie/index"),
      applecalendar: import("./applecalendar/index"),
      caldavcalendar: import("./caldavcalendar/index"),
      cron: import("./cron/index"),
      exchange2013calendar: import("./exchange2013calendar/index"),
      exchange2016calendar: import("./exchange2016calendar/index"),
      exchangecalendar: import("./exchangecalendar/index"),
      feishucalendar: import("./feishucalendar/index"),
      googlecalendar: import("./googlecalendar/index"),
      "ics-feedcalendar": import("./ics-feedcalendar/index"),
      larkcalendar: import("./larkcalendar/index"),
      office365calendar: import("./office365calendar/index"),
      vimcal: import("./vimcal/index"),
      zohocalendar: import("./zohocalendar/index"),
    };
