/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
// Return empty map during E2E tests to prevent module loading issues
export const PaymentServiceMap = process.env.NEXT_PUBLIC_IS_E2E
  ? {}
  : {
      alby: import("./alby/index"),
      hitpay: import("./hitpay/index"),
      "mock-payment-app": import("./mock-payment-app/index"),
      paypal: import("./paypal/index"),
      stripepayment: import("./stripepayment/index"),
    };
