/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
// Return empty map during E2E tests to prevent module loading issues
export const VideoAdapterMap = process.env.NEXT_PUBLIC_IS_E2E
  ? {}
  : {
      campfire: import("./campfire/index"),
      dailyvideo: import("./dailyvideo/index"),
      demodesk: import("./demodesk/index"),
      dialpad: import("./dialpad/index"),
      discord: import("./discord/index"),
      eightxeight: import("./eightxeight/index"),
      "element-call": import("./element-call/index"),
      facetime: import("./facetime/index"),
      googlevideo: import("./googlevideo/index"),
      "horizon-workrooms": import("./horizon-workrooms/index"),
      huddle01video: import("./huddle01video/index"),
      jelly: import("./jelly/index"),
      jitsivideo: import("./jitsivideo/index"),
      mirotalk: import("./mirotalk/index"),
      nextcloudtalk: import("./nextcloudtalk/index"),
      office365video: import("./office365video/index"),
      ping: import("./ping/index"),
      riverside: import("./riverside/index"),
      roam: import("./roam/index"),
      salesroom: import("./salesroom/index"),
      shimmervideo: import("./shimmervideo/index"),
      sirius_video: import("./sirius_video/index"),
      skype: import("./skype/index"),
      sylapsvideo: import("./sylapsvideo/index"),
      tandemvideo: import("./tandemvideo/index"),
      "event-type-location-video-static": import("./templates/event-type-location-video-static/index"),
      webex: import("./webex/index"),
      whereby: import("./whereby/index"),
      zoomvideo: import("./zoomvideo/index"),
    };
